x-app: &app
  # build:
  #   context: .
  #   args:
  #     RUBY_VERSION: '3.2'
  #     PG_MAJOR: '14'
  #     NODE_VERSION: '20'
  # image: mastodon-dev:1.0.0
  image: palkan/mastodon-test-prof:1.0.0
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
  networks:
    - second_internal_network
    - second_external_network
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - second_rails_cache:/app/tmp/cache
    - second_rails_logs:/app/log
    - second_node_modules:/app/node_modules
    - second_history:/usr/local/hist
    - second_storage:/app/public/system
    - ./.psqlrc:/root/.psqlrc:ro
    - ./.bashrc:/root/.bashrc:ro
  environment: &backend_environment
    <<: *env
    BIND: 0.0.0.0
    REDIS_HOST: second_redis
    REDIS_PORT: '6379'
    DB_HOST: second_postgres
    DB_USER: postgres
    DB_PASS: postgres
    DB_PORT: '5432'
    ES_ENABLED: 'false'
    REDIS_URL: redis://second_redis:6379/
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    BOOTSNAP_CACHE_DIR: /app/tmp/cache/bootsnap
    XDG_DATA_HOME: /app/tmp/cache
    YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
    HISTFILE: /usr/local/hist/.bash_history
    PSQL_HISTFILE: /usr/local/hist/.psql_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi
  networks:
    - second_internal_network
    - second_external_network
  depends_on:
    second_postgres:
      condition: service_healthy
    second_redis:
      condition: service_healthy

services:
  second_rails:
    <<: *backend
    command: bundle exec rails

  second_web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      second_sidekiq:
        condition: service_started

  second_sidekiq:
    <<: *backend
    command: bundle exec sidekiq

  second_postgres:
    image: postgres:14
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - second_postgres:/var/lib/postgresql/data
      - second_history:/usr/local/hist
    environment:
      PSQL_HISTFILE: /usr/local/hist/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks:
      - second_internal_network
      - second_external_network

  second_redis:
    image: redis:7.0-alpine
    volumes:
      - second_redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - second_internal_network
      - second_external_network

volumes:
  second_bundle:
  second_node_modules:
  second_history:
  second_rails_cache:
  second_rails_logs:
  second_postgres:
  second_redis:
  second_storage:

networks:
  second_external_network:
  second_internal_network:
    internal: true